control_loop:
  ros__parameters:
    # Control loop frequency [Hz]
    FREQ: 25.0
    # Max base velocities: [m/s], [rad/s]
    V_MAX: 2.0
    V_MIN: 0.1
    W_MAX: 12.6
    W_MIN: 0.314
    # Max motor velocities: [m/s]
    MOTOR_V_MAX: 2.0
    # Distance between drive wheels: [m]
    L: 0.1935
    # P value for rotation during translation
    P_w: 20.0
    # Max base jerk values: [m/s^3], [rad/s^3]
    J_MAX: 60.0
    J_MAX_STOP: 120.0
    J_ROT_MAX: 480.0
    J_ROT_MAX_STOP: 640.0
    # End of movement tolerances: [m], [rad]
    D_TOL: 0.005 # absolute distance from target
    D_PROJ_TOL: 0.0025 # projected distance from target
    D_LONG_TOL: 0.1 # distance before rotation is used fully
    D_SHORT_TOL: 0.05 # minimal distance for rotation during translation
    PHI_TOL: 0.0087 # absolute angle from target

odometry:
  ros__parameters:
    use_sim_time: True
    # Distance between encoder wheels: [m]
    L: 0.297